services:
  db:
    image: postgres:15-alpine
    container_name: swapi_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-swapi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-swapi_password}
      POSTGRES_DB: ${POSTGRES_DB:-swapi_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swapi_user -d swapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: swapi_api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
    command: uvicorn swapi_search.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: