"""Add unique constraint to swapi_resource

Revision ID: 27f5041d3872
Revises: d2df7a02d1eb
Create Date: 2025-07-10 11:26:08.118667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f5041d3872'
down_revision: Union[str, Sequence[str], None] = 'd2df7a02d1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_swapi_resource_type_swapi_id', 'swapi_resource', ['type', 'swapi_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_swapi_resource_type_swapi_id', 'swapi_resource', type_='unique')
    # ### end Alembic commands ###
