"""Create initial swapi_resource table

Revision ID: d2df7a02d1eb
Revises: 
Create Date: 2025-07-09 10:18:38.836416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2df7a02d1eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_table('swapi_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swapi_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('searchable_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swapi_resource_id'), 'swapi_resource', ['id'], unique=False)
    op.create_index('ix_swapi_resource_searchable_text_gin', 'swapi_resource', ['searchable_text'], unique=False, postgresql_using='gin', postgresql_ops={'searchable_text': 'gin_trgm_ops'})
    op.create_index(op.f('ix_swapi_resource_type'), 'swapi_resource', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swapi_resource_type'), table_name='swapi_resource')
    op.drop_index('ix_swapi_resource_searchable_text_gin', table_name='swapi_resource', postgresql_using='gin', postgresql_ops={'searchable_text': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_swapi_resource_id'), table_name='swapi_resource')
    op.drop_table('swapi_resource')
    # ### end Alembic commands ###
